name: recipe_discovery_app
description: A Flutter application for discovering recipes with Clean Architecture and BLoC pattern
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Functional Programming
  dartz: ^0.10.1
  
  # UI Dependencies
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.18.1
  permission_handler: ^11.1.0
  go_router: ^17.0.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
#    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#          weight: 600
